#version 460
#extension GL_EXT_buffer_reference : require
#extension GL_EXT_shader_16bit_storage : require
#extension GL_EXT_shader_explicit_arithmetic_types : require

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

struct ColorBoxData
{
	u16vec2 lo_v;
	u16vec2 hi_v;
	f16vec4 color_rgba;
	uint16_t stack_position;
} ColorBoxData_t;

layout(binding = 5, rgba8) uniform image2D color_buffer;
layout(binding = 6, r16ui) uniform uimage2D depth_buffer;


layout(std430, push_constant) uniform Registers
{
	uint16_t boxes_count;
	RenderDataBuffer boxes;
} registers;

void main()
{
	const u16vec2 batch_size = u16vec2(16);

	const u16vec2 threads_count = u16vec2(gl_WorkGroupSize.xy);
	const u16vec2 thread_group = u16vec2(gl_WorkGroupID.xy);
	const u16vec2 thread_id =  u16vec2(gl_LocalInvocationID.xy);

	for (uint16_t box_id = uint16_t(0); box_id < registers.boxes_count; box_id++)
	{
		const ColorBoxData box_data = registers.boxes.boxes_data[box_id];
		const u16vec2 box_dimensions = (box_data.hi_v - box_data.lo_v);
		const u16vec2 batches_count = box_dimensions / batch_size + min(box_dimensions % batch_size, u16vec2(1));
		const u16vec2 batch_id = threads_count * thread_group + thread_id;

		if (batch_id.x >= batches_count.x || batch_id.y >= batches_count.y)
		{
			continue;
		}

		const u16vec2 batch_boundary_lo = box_data.lo_v + batch_size * batch_id;
		const u16vec2 rest = box_data.hi_v - batch_boundary_lo;
		const u16vec2 expected_pixel_hi = batch_boundary_lo + batch_size;
		const u16vec2 batch_boundary_hi = u16vec2(min(batch_size.x, rest.x), min(batch_size.y, rest.y));

		for (uint16_t y = uint16_t(0); y <= expected_pixel_hi.y; y++)
		{
			for (uint16_t x = uint16_t(0); x <= expected_pixel_hi.x; x++)
			{
				const ivec2 coord = batch_boundary_lo + u16vec2(x, y);
				if (box_data.stack_position > imageLoad(depth_buffer, coord).r)
				{					
					const f16vec4 buffered_color = f16vec4(imageLoad(color_buffer, coord).rgba);
					const float16_t dst_alpha = float16_t(1.0f) - box_data.color_rgba.a;

					imageStore(depth_buffer, coord, u16vec4(box_data.stack_position));
					imageStore(color_buffer, coord, f16vec4(mix(box_data.color_rgba.rgb, buffered_color.rgb, dst_alpha), 1.0f));
				}
				
			}
		}
	}
}